type Query{
  version: String!
  mantainer: String!
  channels(length: Int, search: String, stream: Boolean): [Channel]!
  channel(id: String!): [Channel]!
  countries(length: Int!): [Country]!
  subdivisions: [Subdivision]!
  regions: [Region]!
  blocklists: [Blocklist]!
  streams(length: Int!): [Stream!]!
}
