type Query{
  version: String!
  mantainer: String!
  channels(length: Int!): [Channel]!
  countries(length: Int!): [Country]!
  subdivisions: [Subdivision]!
  regions: [Region]!
  blocklists: [Blocklist]!
  streams: [Stream]!
}
